# Add something like this to Routes.yaml of your distribution, but before Neos routes!
#
# -
#   name: 'Listable'
#   uriPattern: '<ListableSubroutes>'
#   subRoutes:
#     'ListableSubroutes':
#       package: 'Flowpack.Listable'
#       variables:
#         'defaultUriSuffix': ''
#         'pageSeparator': '~p'

-
  name: 'Paginate for Flowpack.Listable:Listable'
  uriPattern:    '{node}<pageSeparator>{--listable-paginate.currentPage}<defaultUriSuffix>'
  defaults:
    '@package':    'Neos.Neos'
    '@controller': 'Frontend\Node'
    '@format':     'html'
    '@action':     'show'
    '--listable-paginate':
      '@package': ''
      '@subpackage': ''
      '@controller': ''
      '@action': 'index'
      'currentPage': '1'
  routeParts:
    node:
      handler: Neos\Neos\Routing\FrontendNodeRoutePartHandler
  appendExceedingArguments: TRUE
